[package]
name = "producer"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
did_iota = { path = "../did_iota" }
did_jwk = { path = "../did_jwk" }
did_key = { path = "../did_key" }
did_web = { path = "../did_web" }
shared = { path = "../shared" }

identity_iota.workspace = true
identity_storage.workspace = true
identity_stronghold.workspace = true
identity_stronghold_ext = { path = "../identity_stronghold_ext", features = ["send-sync-storage"] }
iota-sdk.workspace = true
iota_stronghold.workspace = true
log = "0.4"
serde = "1.0"
serde_json.workspace = true
url = "2.5"


[dev-dependencies]
base64 = "0.22"
hex = "0.4"
test-log.workspace = true
tokio.workspace = true
