[package]
name = "token_wallet"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
shared = { path = "../shared" }

anyhow = "1.0"
iota-sdk = { version = "1.0", features = ["storage", "stronghold"] }
log.workspace = true
rand.workspace = true

[dev-dependencies]
identity_iota.workspace = true
identity_stronghold.workspace = true
iota-crypto = { version = "0.23" }
iota_stronghold = { version = "2.0" }
test-log.workspace = true
tokio.workspace = true
