[package]
name = "did_manager"
version = "0.1.0"
edition = "2021"
description = "Resolve, create and sign DIDs for various methods"
homepage = "https://www.impierce.com/"
license = "Apache-2.0"
repository = "https://github.com/impierce/did-manager"

[workspace]
resolver = "2"
members = [
    "consumer",
    "did_iota",
    "did_jwk",
    "did_key",
    "did_web",
    "identity_stronghold_ext",
    "producer",
    "shared",
]

[dependencies]
consumer = { path = "consumer" }
producer = { path = "producer" }

[workspace.package]
homepage = "https://www.impierce.com/"
license = "Apache-2.0"
repository = "https://github.com/impierce/did-manager"
rust-version = "1.75"

[workspace.dependencies]
identity_iota = { version = "1.5", default-features = false, features = ["resolver", "iota-client"] }
identity_storage = { version = "1.5", default-features = false }
identity_stronghold = { version = "1.5", features = ["send-sync-storage"] }
identity_verification = { version = "1.5", default-features = false }
iota-sdk = { version = "1.1", features = ["stronghold"] }
iota_stronghold = { version = "2.1" }
log = "0.4"
rand = "0.8"
serde_json = "1.0"
signature = "2.2"
ssi-dids = { version = "0.1.1" }
ssi-jwk = { version = "0.1.2", default-features = false, features = [
    "ed25519",
    "secp256r1",
] }
test-log = "0.2"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
