[workspace]
resolver = "2"
members = ["consumer", "did_jwk", "did_key", "did_web"]

[workspace.package]
homepage = "https://www.impierce.com/"
license = "Apache-2.0"
repository = "https://github.com/impierce/did-manager"
rust-version = "1.75"

[workspace.dependencies]
identity_iota = { version = "1.1.0" }
identity_stronghold = { version = "1.1.0" }
iota-sdk = { version = "1.0", features = ["stronghold"] }
tokio = { version = "1", features = ["full"] }

# TODO: Temporarily fixes percent-encoding for did:web method id (https://github.com/iotaledger/identity.rs/issues/1299)
[patch.crates-io]
did_url = { git = "https://github.com/iotaledger/did_url.git" }
