[package]
name = "consumer"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
did_iota = { path = "../did_iota" }
did_jwk = { path = "../did_jwk" }
did_key = { path = "../did_key" }
did_web = { path = "../did_web" }
shared = { path = "../shared" }

identity_iota.workspace = true
rustls = { version = "0.23", features = ["ring"] }
signature.workspace = true
tokio.workspace = true

[dev-dependencies]
test-log.workspace = true
