[package]
name = "did_iota"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
shared = { path = "../shared" }

bls12_381_plus = "=0.8.15"           # TODO: if not pinned, we get an error: "conflicting implementations of trait `From<bls12_381_plus::scalar::Scalar>` for type `Issuer`"
identity_iota.workspace = true
identity_stronghold.workspace = true
iota-sdk.workspace = true
log.workspace = true
tokio.workspace = true

[dev-dependencies]
iota_stronghold = { version = "2.1" }
serde_json.workspace = true
test-log.workspace = true
