[package]
name = "did_iota"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
shared = { path = "../shared" }

identity_iota.workspace = true
identity_stronghold.workspace = true
iota-sdk.workspace = true
log.workspace = true
tokio.workspace = true

[dev-dependencies]
iota_stronghold = { version = "2.1" }
serde_json.workspace = true
test-log.workspace = true
