[package]
name = "identity_stronghold_ext"
version = "0.1.0"
edition = "2021"
description = "Secure JWK storage with Stronghold Ext for IOTA Identity"
homepage = "https://www.impierce.com/"
license = "Apache-2.0"
repository = "https://github.com/impierce/did-manager"
keywords = ["iota", "storage", "identity", "kms", "stronghold"]

[dependencies]
async-trait = { version = "0.1.64", default-features = false }
elliptic-curve = { version = "0.13", features = ["jwk"] }
identity_storage.workspace = true
identity_verification.workspace = true
iota-sdk-legacy.workspace = true
iota_stronghold.workspace = true
k256 = { version = "0.13", features = ["jwk"] }
log.workspace = true
p256 = { version = "0.13", features = ["jwk"] }
rand = { version = "0.8.5", default-features = false, features = [
    "std",
    "std_rng",
] }
serde_json.workspace = true
secret-storage = { git = "https://github.com/iotaledger/secret-storage", tag = "v0.3.0" }
stronghold_ext = { git = "https://github.com/impierce/stronghold_ext.git", features = [
    "crypto",
] }
tokio.workspace = true

[dev-dependencies]
hex = "0.4"
test-log.workspace = true

[features]
default = []
# Enables `Send` + `Sync` bounds for the trait implementations on `StrongholdStorage`.
send-sync-storage = ["identity_storage/send-sync-storage"]
