[package]
name = "shared"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
test = []

[dependencies]
identity_stronghold_ext = { path = "../identity_stronghold_ext", features = ["send-sync-storage"] }

identity_iota.workspace = true
identity_stronghold.workspace = true
iota-sdk.workspace = true
iota_stronghold.workspace = true
log.workspace = true
rand = "0.8"
thiserror.workspace = true

serde_json.workspace = true
identity_storage = { git = "https://github.com/iotaledger/identity.rs", default_features = false }
