[package]
name = "did_jwk"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
identity_stronghold_ext = { path = "../identity_stronghold_ext", features = ["send-sync-storage"] }
shared = { path = "../shared" }
did-jwk-extern = { version = "0.1.1", package = "did-jwk" }
identity_iota.workspace = true
identity_stronghold.workspace = true
iota-sdk.workspace = true
log.workspace = true
serde_json.workspace = true
ssi-dids = "0.1.1"
ssi-jwk = "0.1.2"
tokio.workspace = true

identity_storage = { git = "https://github.com/iotaledger/identity.rs", default_features = false }

[dev-dependencies]
test-log.workspace = true
