[package]
name = "did_web"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
shared = { path = "../shared" }
did-web-extern = { git = "https://github.com/impierce/spruceid-ssi.git", package = "did-web" }
identity_iota.workspace = true
identity_storage.workspace = true
identity_stronghold.workspace = true
iota-sdk.workspace = true
log.workspace = true
serde_json.workspace = true
ssi-dids = { git = "https://github.com/impierce/spruceid-ssi.git" }
ssi-jwk = "0.1.2"
tokio.workspace = true
url = "2.5"
urlencoding = "2.1"

[dev-dependencies]
shared = { path = "../shared", features = ["test"] }
test-log.workspace = true
wiremock = "0.5"
